name: Maven CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build API with Maven
        run: mvn -B package --file pom.xml
        working-directory: api

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Download frontend dependencies
        run: npm install
        working-directory: front-end

      - name: Build frontend with NPM
        run: npm run build
        working-directory: front-end
